//"768 12 4 1",
//"  c black",
//". c white",
//"X c None",
const char FONT[12][768] = {
	"XXXXXXXXXXX    XX      XXX     XXXX   XXX   X   XX   XXXXX    XXXXXX   XX   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   XX     XXX    XXX      XX      XXXX    X        XXX    X        X      XX      XXXXXXXXXXXXXXXXXXXXX    XXXXXXXX    XXXXX      XX      XXX     XX      XXX     XX     XXX       X       XX     XX       XX   XXXXXXX    X   X   X    XXX   XX       X   X      XX      XXX     XX      XX      X                   XX      XX      XX      XX           XX     X   XX   X     XXXX    XXXXXXXXXXXX   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXX   XXX    XXXX       XXXXXXXX",
	"XXXXXXXXXXX .. XX .  . XXX . . XXX  .     .   . X  .  XXXX .. XXXXX  . XX .  XXXXXX   XXXXX   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  . X  ...  X  .. XX  ....    ....  XX  .. X ...... XX  .. X ......   ....    ....  XX    XXXX    XXXXX  .. XXXXXXXX ..  XXX  ....    ....  X  ... XX ....  X  ...  X ...  XX ..... X ..... X  ...  X .. .. XX .  XXXXXX .. X .   . X .. XXX . XX .  ..   .   ....    ....  X  ...    ....    ....   ......  ..  ..  .  X .  . XX .  .    .  . XX .  ...... XX ... X . XX . X ... XXX  ..  XXXXXXXXXXX .  XXXXXXXXXXX    XXXXXXXXXXXXXXX    XXXXXXXXXXX    XXXXXXXXXX   XXXXXX    XXXX    XX    XXXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  .. XXXX . XXX ..  XX  ..  . XXXXXXXX",
	"XXXXXXXXXXX .. X  .  . XX  . .  X  ....  . . .  X . . XXXX  . XXXXX .  XX  . XXXX   .   XXX . XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX .  X .. .. X ... XX ..  ..  ..  .. XX ... X ..     X  ..  X ..  ..  ..  ..  ..  .. XX .. XXXX .. XXXX  ..  X         ..  XX ..  ..  .    . X ....  X .  .. X ..  . X .  .  X .       .     X .. .. X .. .. XX .. XXXXXX .. X .  .. X .. XXX .    .  ..  ..  ..  ..  ..   . X ..  .  ..   .  ..   .  ......  ..  ..  .. X .  . XX .  ..  ..  .    .       . XX .   X .    . X   . XXX .  . XXXXXXXXXXX  . XXX     XXX .. XXXXX     XXXXX .. XX     XXX  ..  XX      X . XXXXXX .. XXXX .. XX .. XXXXXX .. XX       X       XX      X       XX              XX      XXX . XXX       X   XX      XX      XX      XX           XX .   XXXX . XXX   . XX .  ..  XXXXXXXX",
	"XXXXXXXXXX  .. X .  .  XX ..... X . .    . . . XX . . XXXX .  XXXX  . XXXX .  XXX . . . XXX . XXXXXXXXXXXXXXXXXXXXXXXXXXXXX  . XX .  .. X ... XX ..  ..  ..  .. X  . . X ..    XX ..   X ..  ..  ..  ..  ..  .. XX .. XXXX .. XXX  ..  XX ..... X  ..  X ..  ..  . .. . X .. .. X .  ..   .     X .   . X .   XX .. XXXX  .   . X .. .. XX .. XXXXXX .. X . ..  X .. XXX ..  ..  ..  ..  .    .  .. X . X .   .  .  X .  ..        ..    ..  ..  ..   .  .    .   .  .   ..  .. XXX  .. XX . XXX  .  .  XXX . XXX      XXXXXXXXXXXX   XX  ...  XX .  XXXX  ...  XXXX .  X  ...  XX .  . X  .. . X . XXXXXX    XXXX    XX  .    XXX .. XX . . .   . ...    ....   .. ..    .. ..  .. ..    ....  X  .   X ..  . X .  X .  . XX .  .    .  . XX .  ...... XX . XXXXXX . XXXXX . XX       XXXXXXXXX",
	"XXXXXXXXXX ..  X      XXX  . .  X . .  X  . .  XX  .  XXXX   XXXXX .  XXXX  . XXX  ...  X   .   XXXXXXXXX      XXXXXXXXXXXX .  X  .  .. X  .. XX     ..     ..  X .. . X .....    ....      ..    ....   ..  .. XX    XXXX    XX  ..  XXX       XX  ..      ..   .. . .   .  ..   ....   .. XXXX  . X . X ...  X ..    X ..       .  .. XX .. XXXXXX ..   ...  X  .. XXX ......  ... ..  . XX .  ..   .   . X .  .    .   ...  XXX .. XX ..  ..  ..  ..  . .. . X  ..  X  .  .  XX  ..  XX . XXX  .  .  XXX . XXXXXXXXXXXXXXXXXXXXXXXXXX .   . XX .    XX ..  . X    . XX .   . XX .      .. .. X .    XXX .  XXXX .. XXX .  . XXX .. XX ......  ... ..  ..  ..   ..  .  .  ..    ..  .  ..   . X .... X ..  . X .. X .  .    .   .  .   .    .      .. X  . XXXXXX . XXXXX .  XXXXXXXXXXXXXXXXX",
	"XXXXXXXXXX .. XXXXXXXXXXX .  . XX  ...  X  ..  X  . . XXXXXXXXXXXX . XXXXXX . XXXX  .  XX ..... XXXXXXXXX .... XXXXXXXXXXX  . XX ..  .. XX .. XXXX  ..  XXX ...   .  .       ..  ..  .. XX  .. X  .. .    ..... XXXXXXXXXXXXXXXX ..  XXXXXXXXXXXXXX  .. XX ..  X .. . .  ..  ..  .....   .. XXXX .. X .   .... X ..... X .. ...  ...... XX .. XX     ..  ...  XX ..  XXX .... .  ... ..  . XX .  ..  ..  ..   .  ..  .  X   ..  XX .. XX ..  ..   .. .   . .. . XX .. XXX .... XX  ..  XXX . XXX ...... XXX . XXXXXXXXXXXXXXXXXXXXXXXXXX   ... XX . ..    .     X .... X  .   .    .     ..   . X ....  XX .. XXXX  . XXX . .. XXX .. XX .. . .  ..   .  .    . X ..  .  .  .. XX ..  .  ..     X  .   X ..  . X ..   .  . .. . X  ..  X  .  .  XX  ..  X .  XXXXXX . XXXXX  . XXXXXXXXXXXXXXXXX",
	"XXXXXXXXXX .. XXXXXXXXXX  . .  XXX  . . X  . .   .  .   XXXXXXXXXX .  XXXX  . XXX  ...  X   .   XXXXXXXXX      XXXXXXXXXXX .  XX ..  .. XX .. XXX  ..  X     ..  .. ...      ..  ..  .. XX ..  X ..  .. X   ..  XXXXXXXXXXXXXXXX  ..  XXX       XX  ..  XX .. XX .. ..   ......  ..  ..  ..      ..   .  ..    X ..    X ..   .  ...... XX .. XX ..  ..  ....  X .. XXXX .    .  ......  .    .  .....   .. . .  .....       .. XX .. XX ..  .. X .. . X ...... X  ..  XX  ..  X  ..  XXXX . XXX   ..   XXX . XXXXXXXXXXXXXXXXXXXXXXXXXX  .  . X  ..  .  .. XXXX  .  . X .....   ......  ..  ..   ..  . XX .. XXXXX . XX  ...  XXX .. XX .. . .  .. X .  . XX .   ..  .  .  ..    .       ....  XX .     ..  . X  .. .   .....  X  ..  XX .  . XX  ..  XX  . XXXXXX . XXXXX .  XXXXXXXXXXXXXXXXX",
	"XXXXXXXXXX    XXXXXXXXXX ..... XX  .  . X . . .  .  . . XXXXXXXXXX  . XXXX .  XXX . . . XXX . XXXX    XXXXXXXXXXXX    XXX  . XXX ..  .. XX .. XX  ..     ..  ..  ......  ..  ..  ..  .. XX .. XX ..  .. XX  .. XXX    XXXX    XXX  ..  XX ..... X  ..  XXX    XX . .     ......  ..  ..  ...  .  ..  ..  ..      .. XXXX ..  ..  ..  .. XX .. XX ..  ..  .. ..   ..      . XX .  .. ...  ..  ..  ..    X ..  ..  ..  ..  ..  .. XX .. XX ... .. X .... X  .. .    ....  XX .. XX ..     XX . XXX ...... XXX . XXXXXXXXXXXXXXXXXXXXXXXXXX ..  . X ..  ..  ..      ..  .   ..        ..     ... .  ..   . XX .. XX    . XX ....  XXX .. XX .. . .  .. X .  .    .  .. ..    .. ..  .. XXXX     .. XX .  .  ..  . XX .. . X  .. . X  ....  X  ... X  ..  XXXX . XXXXXX . XXXXX . XXXXXXXXXXXXXXXXXX",
	"XXXXXXXXXX .. XXXXXXXXXX  . .  XX ....    . . .  .   .  XXXXXXXXXXX .  XX  . XXXX   .   XXX . XXXX .. XXXXXXXXXXXX .. XXX .  XXX .. ..  XX .. XX ......  ......     ..   ......  ...... XX .. XX ...... XX ... XXX .. XXXX .. XXXX  ..  X         ..  XXXX .. XX .   ..  ..  ..  ......   .....  .....   ......  .. XXXX .....   ..  .. XX .. XX ......  ..  ..  ......  . XX .  ..  ..  ......  .. XXXX .....   ..  ..  ...... XX .. XX ...... X  ..  XX .  . X ..  .. XX .. XX ...... XX .   X   ..   X   . XXXXXXXXXX        XXXXXXXX .....   .....   ... ..  ......  ...  . XX .. XXX    ..  .. X . XX .. XX .  . XX .. ..  XX .. XX .. . .  .. X .  ..  ..  ..    XX    ..  .. XXXX ..  .. XX ....  .....  X  ..  XX .  . X ..  .. XX  .  X ...    XX .   XXXX . XXX   . XXXXXXXXXXXXXXXXXX",
	"XXXXXXXXXX .. XXXXXXXXXXX . . XXX  .   X .   .    ... . XXXXXXXXXXX  . XX .  XXXXXX   XXXXX   XXXX  . XXXXXXXXXXXX .. XX  . XXXX  .... XXX .. XX ......   ....  XXX .. X  ....    ....  XX .. XX  ....  XX ..  XXX .. XXXX  . XXXXX  .. XXXXXXXX ..  XXXXX .. XX  ....   ..  ..  .....  X  ...   ....  X ......  .. XXXX  ...  X ..  .. XX .. XX  ....   ..   .  ......  . XX .  ..  ..   ....   .. XXXX  ... .  ..  ..   ....  XX .. XX  ....  XX .. XXX .  . X ..  .. XX .. XX ...... XX ... XXX .. XXX ... XXXXXXXXXX ...... XXXXXXXX  ... .   ...  X  ....    ... .   ....  XX .. XXX  ...   .. X . XX .. XX .... XX ..  .. XX .. XX .. . .  .. X .   ....   .. XXXXXXXX ..  .. XXXX  ....  XX  ..    ... . XX .. XXX .  . X .    . X  .. XX ...... XX  .. XXXX . XXX ..  XXXXXXXXXXXXXXXXXX",
	"XXXXXXXXXX    XXXXXXXXXXX     XXXX   XXX   X   XX       XXXXXXXXXXXX   XX   XXXXXXXXXXXXXXXXXXXXXX .  XXXXXXXXXXXX    XX .  XXXXX      XXX    XX        X      XXXX    XX      XX      XXX    XXX      XXX    XXXX    XXXX .  XXXXXX    XXXXXXXX    XXXXXX    XXX      X               XXX     X      XX            XXXXX     XX        XX    XXX      X    X              XX           X      X    XXXXX               X      XXX    XXX      XXX    XXX      X        XX    XX        XX     XXX    XXX     XXXXXXXXXX        XXXXXXXXX       X     XXX      XX       X      XXX    XXX ...  X    X   XX    XX  ..  XX    X   XX    XX            X   X      X .. XXXXXXXX ..     XXXXX      XXXX    XX       XX    XXX      X   XX   X ..  XX        XXX    XXXX   XXX    XXXXXXXXXXXXXXXXXXX",
	"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   XXXXXXXXXXXXXXXXXXX   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX     XXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
};
