const char Wheel_frames[16][32][32] = { //[frame][y][x]
	{
		"oooooooooooo   ..   oooooooooooo",
		"ooooooooo      ..      ooooooooo",
		"ooooooo        ..        ooooooo",
		"oooooo         ..         oooooo",
		"ooooo          ..          ooooo",
		"oooo           ..           oooo",
		"ooo            ..            ooo",
		"oo             ..             oo",
		"oo             ..             oo",
		"o              ..              o",
		"o              ..              o",
		"o              ..              o",
		"               ..               ",
		"               ..               ",
		"               ..               ",
		"................................",
		"................................",
		"               ..               ",
		"               ..               ",
		"               ..               ",
		"o              ..              o",
		"o              ..              o",
		"o              ..              o",
		"oo             ..             oo",
		"oo             ..             oo",
		"ooo            ..            ooo",
		"oooo           ..           oooo",
		"ooooo          ..          ooooo",
		"oooooo         ..         oooooo",
		"ooooooo        ..        ooooooo",
		"ooooooooo      ..      ooooooooo",
		"oooooooooooo   ..   oooooooooooo",
	},{
		"oooooooooooo  ..    oooooooooooo",
		"ooooooooo     ..       ooooooooo",
		"ooooooo       ..         ooooooo",
		"oooooo        ..          oooooo",
		"ooooo         ..           ooooo",
		"oooo          ..            oooo",
		"ooo           ..             ooo",
		"oo            ..              oo",
		"oo            ..              oo",
		"o             ..               o",
		"o             ...              o",
		"o             ...              o",
		"               ..               ",
		"               ..               ",
		"               ..   ............",
		"          ......................",
		"......................          ",
		"............   ..               ",
		"               ..               ",
		"               ..               ",
		"o              ...             o",
		"o              ...             o",
		"o               ..             o",
		"oo              ..            oo",
		"oo              ..            oo",
		"ooo             ..           ooo",
		"oooo            ..          oooo",
		"ooooo           ..         ooooo",
		"oooooo          ..        oooooo",
		"ooooooo         ..       ooooooo",
		"ooooooooo       ..     ooooooooo",
		"oooooooooooo    ..  oooooooooooo",
	},{
		"oooooooooooo..      oooooooooooo",
		"ooooooooo   ..         ooooooooo",
		"ooooooo     ..           ooooooo",
		"oooooo      ...           oooooo",
		"ooooo        ..            ooooo",
		"oooo         ..             oooo",
		"ooo          ..              ooo",
		"oo           ..               oo",
		"oo           ...              oo",
		"o             ..               o",
		"o             ..               o",
		"o             ..               o",
		"              ..            ....",
		"              ...      .........",
		"               .. ...........   ",
		"             ...........        ",
		"        ...........             ",
		"   ........... ..               ",
		".........      ...              ",
		"....            ..              ",
		"o               ..             o",
		"o               ..             o",
		"o               ..             o",
		"oo              ...           oo",
		"oo               ..           oo",
		"ooo              ..          ooo",
		"oooo             ..         oooo",
		"ooooo            ..        ooooo",
		"oooooo           ...      oooooo",
		"ooooooo           ..     ooooooo",
		"ooooooooo         ..   ooooooooo",
		"oooooooooooo      ..oooooooooooo",
	},{
		"oooooooooooo        oooooooooooo",
		"ooooooooo  ..          ooooooooo",
		"ooooooo    ..            ooooooo",
		"oooooo     ..             oooooo",
		"ooooo      ...             ooooo",
		"oooo        ..              oooo",
		"ooo         ..               ooo",
		"oo          ...               oo",
		"oo           ..               oo",
		"o            ..                o",
		"o            ..                o",
		"o             ..           ....o",
		"              ..        ....... ",
		"              ..     .......    ",
		"               .. .......       ",
		"              .......           ",
		"           .......              ",
		"       ....... ..               ",
		"    .......     ..              ",
		" .......        ..              ",
		"o....           ..             o",
		"o                ..            o",
		"o                ..            o",
		"oo               ..           oo",
		"oo               ...          oo",
		"ooo               ..         ooo",
		"oooo              ..        oooo",
		"ooooo             ...      ooooo",
		"oooooo             ..     oooooo",
		"ooooooo            ..    ooooooo",
		"ooooooooo          ..  ooooooooo",
		"oooooooooooo        oooooooooooo",
	},{
		"oooooooooooo        oooooooooooo",
		"ooooooooo..            ooooooooo",
		"ooooooo  ...             ooooooo",
		"oooooo    ..              oooooo",
		"ooooo     ..               ooooo",
		"oooo       ..               oooo",
		"ooo        ..                ooo",
		"oo         ...                oo",
		"oo          ..                oo",
		"o           ..               ..o",
		"o            ..           .....o",
		"o            ..         ...... o",
		"             ...      .....     ",
		"              ..   ......       ",
		"              ........          ",
		"              ......            ",
		"            ......              ",
		"          ........              ",
		"       ......   ..              ",
		"     .....      ...             ",
		"o ......         ..            o",
		"o....            ..            o",
		"o..               ..           o",
		"oo                ..          oo",
		"oo                ...         oo",
		"ooo                ..        ooo",
		"oooo               ...      oooo",
		"ooooo               ..     ooooo",
		"oooooo              ..    oooooo",
		"ooooooo             ...  ooooooo",
		"ooooooooo            ..ooooooooo",
		"oooooooooooo        oooooooooooo",
	},{
		"oooooooooooo        oooooooooooo",
		"ooooooooo.             ooooooooo",
		"ooooooo ..               ooooooo",
		"oooooo  ...               oooooo",
		"ooooo    ..                ooooo",
		"oooo     ...                oooo",
		"ooo       ..                 ooo",
		"oo        ...                 oo",
		"oo         ..               ..oo",
		"o          ...            .....o",
		"o           ..          .....  o",
		"o           ...       .....    o",
		"             ..     .....       ",
		"              ..  .....         ",
		"              .......           ",
		"              .....             ",
		"             .....              ",
		"           .......              ",
		"         .....  ...             ",
		"       .....     ..             ",
		"o    .....       ...           o",
		"o  .....          ..           o",
		"o.....            ...          o",
		"oo..               ..         oo",
		"oo                 ...        oo",
		"ooo                 ..       ooo",
		"oooo                ...     oooo",
		"ooooo                ..    ooooo",
		"oooooo                ..  oooooo",
		"ooooooo               .. ooooooo",
		"ooooooooo             .ooooooooo",
		"oooooooooooo        oooooooooooo",
	},{
		"oooooooooooo        oooooooooooo",
		"ooooooooo              ooooooooo",
		"ooooooo.                 ooooooo",
		"oooooo...                 oooooo",
		"ooooo  ...                 ooooo",
		"oooo    ..                  oooo",
		"ooo     ...                 .ooo",
		"oo       ...               ...oo",
		"oo        ..             .... oo",
		"o         ...           ....   o",
		"o          ...        ....     o",
		"o           ..       ....      o",
		"            ...    ....         ",
		"             ...  ....          ",
		"              ......            ",
		"              .....             ",
		"             .....              ",
		"            ......              ",
		"          ....  ...             ",
		"         ....    ...            ",
		"o      ....       ..           o",
		"o     ....        ...          o",
		"o   ....           ...         o",
		"oo ....             ..        oo",
		"oo...               ...       oo",
		"ooo.                 ...     ooo",
		"oooo                  ..    oooo",
		"ooooo                 ...  ooooo",
		"oooooo                 ...oooooo",
		"oooooooo                .ooooooo",
		"ooooooooo              ooooooooo",
		"oooooooooooo        oooooooooooo",
	},{
		"oooooooooooo        oooooooooooo",
		"ooooooooo              ooooooooo",
		"ooooooo                  ooooooo",
		"oooooo.                   oooooo",
		"ooooo...                   ooooo",
		"oooo  ...                  .oooo",
		"ooo    ...                ...ooo",
		"oo      ..               ...  oo",
		"oo       ..            ....   oo",
		"o        ...          ....     o",
		"o         ...        ...       o",
		"o          ...      ...        o",
		"            ...    ...          ",
		"             ..  ....           ",
		"             ......             ",
		"              ....              ",
		"              ....              ",
		"            .......             ",
		"           ....  ..             ",
		"          ...     ..            ",
		"o        ...      ...          o",
		"o       ...        ...         o",
		"o     ....          ...        o",
		"oo   ...             ...      oo",
		"ooo ...               ..      oo",
		"ooo...                 ..    ooo",
		"oooo.                  ...  oooo",
		"ooooo                   ...ooooo",
		"oooooo                   .oooooo",
		"oooooooo                 ooooooo",
		"ooooooooo              ooooooooo",
		"oooooooooooo        oooooooooooo",
	},{
		"oooooooooooo        oooooooooooo",
		"ooooooooo              ooooooooo",
		"ooooooo                  ooooooo",
		"oooooo                    oooooo",
		"ooooo.                    .ooooo",
		"oooo...                  ...oooo",
		"ooo  ...                ...  ooo",
		"oo    ...              ...    oo",
		"oo     ...            ...     oo",
		"o       ...          ...       o",
		"o        ...        ...        o",
		"o         ...      ...         o",
		"           ...    ...           ",
		"            ...  ...            ",
		"             ......             ",
		"              ....              ",
		"              ....              ",
		"             ......             ",
		"            ...  ...            ",
		"           ...    ...           ",
		"o         ...      ...         o",
		"o        ...        ...        o",
		"o       ...          ...       o",
		"oo     ...            ...     oo",
		"oo    ...              ...    oo",
		"ooo  ...                ...  ooo",
		"oooo...                  ...oooo",
		"ooooo.                    .ooooo",
		"oooooo                    oooooo",
		"ooooooo                  ooooooo",
		"ooooooooo              ooooooooo",
		"oooooooooooo        oooooooooooo",
	},{
		"oooooooooooo        oooooooooooo",
		"ooooooooo              ooooooooo",
		"ooooooo                  ooooooo",
		"oooooo                   .oooooo",
		"ooooo                   ...ooooo",
		"oooo.                  ...  oooo",
		"ooo...                ...    ooo",
		"oo  ...               ..      oo",
		"oo   ....            ...      oo",
		"o     ....          ...        o",
		"o       ...        ...         o",
		"o        ...      ...          o",
		"          ...     ..            ",
		"           ....  ..             ",
		"             ......             ",
		"              ....              ",
		"              ....              ",
		"             .......            ",
		"             ..  ....           ",
		"            ..     ...          ",
		"o          ...      ...        o",
		"o         ...        ...       o",
		"o        ...          ....     o",
		"oo       ..             ...   oo",
		"oo      ..               ...  oo",
		"ooo    ...                ...ooo",
		"oooo  ...                  .oooo",
		"ooooo...                   ooooo",
		"oooooo.                   oooooo",
		"ooooooo                  ooooooo",
		"ooooooooo              ooooooooo",
		"oooooooooooo        oooooooooooo",
	},{
		"oooooooooooo        oooooooooooo",
		"ooooooooo              ooooooooo",
		"ooooooo                 .ooooooo",
		"oooooo                 ...oooooo",
		"ooooo                 ...  ooooo",
		"oooo                  ..    oooo",
		"ooo.                 ...     ooo",
		"oo...               ...       oo",
		"oo ....             ..        oo",
		"o   ....           ...         o",
		"o     ....        ...          o",
		"o      ....       ..           o",
		"         ....    ...            ",
		"          ....  ...             ",
		"            ......              ",
		"             .....              ",
		"              .....             ",
		"              ......            ",
		"             ...  ....          ",
		"            ...    ....         ",
		"o           ..       ....      o",
		"o          ...        ....     o",
		"o         ...           ....   o",
		"oo        ..             .... oo",
		"oo       ...               ...oo",
		"ooo     ...                 .ooo",
		"oooo    ..                  oooo",
		"ooooo  ...                 ooooo",
		"oooooo...                 oooooo",
		"ooooooo.                 ooooooo",
		"ooooooooo              ooooooooo",
		"oooooooooooo        oooooooooooo",
	},{
		"oooooooooooo        oooooooooooo",
		"ooooooooo             .ooooooooo",
		"ooooooo               .. ooooooo",
		"oooooo               ...  oooooo",
		"ooooo                ..    ooooo",
		"oooo                ...     oooo",
		"ooo                 ..       ooo",
		"oo                 ...        oo",
		"oo..               ..         oo",
		"o.....            ...          o",
		"o  .....          ..           o",
		"o    .....       ...           o",
		"       .....     ..             ",
		"         .....  ...             ",
		"           .......              ",
		"             .....              ",
		"              .....             ",
		"              .......           ",
		"             ...  .....         ",
		"             ..     .....       ",
		"o           ...       .....    o",
		"o           ..          .....  o",
		"o          ...            .....o",
		"oo         ..               ..oo",
		"oo        ...                 oo",
		"ooo       ..                 ooo",
		"oooo     ...                oooo",
		"ooooo    ..                ooooo",
		"oooooo  ...               oooooo",
		"ooooooo ..               ooooooo",
		"ooooooooo.             ooooooooo",
		"oooooooooooo        oooooooooooo",
	},{
		"oooooooooooo        oooooooooooo",
		"ooooooooo            ..ooooooooo",
		"ooooooo             ...  ooooooo",
		"oooooo              ..    oooooo",
		"ooooo               ..     ooooo",
		"oooo               ..       oooo",
		"ooo                ..        ooo",
		"oo                ...         oo",
		"oo                ..          oo",
		"o..               ..           o",
		"o.....           ..            o",
		"o ......         ..            o",
		"     .....      ...             ",
		"       ......   ..              ",
		"          ........              ",
		"            ......              ",
		"              ......            ",
		"              ........          ",
		"              ..   ......       ",
		"             ...      .....     ",
		"o            ..         ...... o",
		"o            ..            ....o",
		"o           ..               ..o",
		"oo          ..                oo",
		"oo         ...                oo",
		"ooo        ..                ooo",
		"oooo       ..               oooo",
		"ooooo     ..               ooooo",
		"oooooo    ..              oooooo",
		"ooooooo  ...             ooooooo",
		"ooooooooo..            ooooooooo",
		"oooooooooooo        oooooooooooo",
	},{
		"oooooooooooo        oooooooooooo",
		"ooooooooo          ..  ooooooooo",
		"ooooooo            ..    ooooooo",
		"oooooo             ..     oooooo",
		"ooooo             ...      ooooo",
		"oooo              ..        oooo",
		"ooo               ..         ooo",
		"oo               ...          oo",
		"oo               ..           oo",
		"o                ..            o",
		"o                ..            o",
		"o....           ..             o",
		" .......        ..              ",
		"    .......     ..              ",
		"       ....... ..               ",
		"           .......              ",
		"              .......           ",
		"               .. .......       ",
		"              ..     .......    ",
		"              ..        ....... ",
		"o             ..           ....o",
		"o            ..                o",
		"o            ..                o",
		"oo           ..               oo",
		"oo          ...               oo",
		"ooo         ..               ooo",
		"oooo        ..              oooo",
		"ooooo      ...             ooooo",
		"oooooo     ..             oooooo",
		"ooooooo    ..            ooooooo",
		"ooooooooo  ..          ooooooooo",
		"oooooooooooo        oooooooooooo",
	},{
		"oooooooooooo      ..oooooooooooo",
		"ooooooooo         ..   ooooooooo",
		"ooooooo           ..     ooooooo",
		"oooooo           ...      oooooo",
		"ooooo            ..        ooooo",
		"oooo             ..         oooo",
		"ooo              ..          ooo",
		"oo               ..           oo",
		"oo              ...           oo",
		"o               ..             o",
		"o               ..             o",
		"o               ..             o",
		"....            ..              ",
		".........      ...              ",
		"   ........... ..               ",
		"        ...........             ",
		"             ...........        ",
		"               .. ...........   ",
		"              ...      .........",
		"              ..            ....",
		"o             ..               o",
		"o             ..               o",
		"o             ..               o",
		"oo           ...              oo",
		"oo           ..               oo",
		"ooo          ..              ooo",
		"oooo         ..             oooo",
		"ooooo        ..            ooooo",
		"oooooo      ...           oooooo",
		"ooooooo     ..           ooooooo",
		"ooooooooo   ..         ooooooooo",
		"oooooooooooo..      oooooooooooo",
	},{
		"oooooooooooo    ..  oooooooooooo",
		"ooooooooo       ..     ooooooooo",
		"ooooooo         ..       ooooooo",
		"oooooo          ..        oooooo",
		"ooooo           ..         ooooo",
		"oooo            ..          oooo",
		"ooo             ..           ooo",
		"oo              ..            oo",
		"oo              ..            oo",
		"o               ..             o",
		"o              ...             o",
		"o              ...             o",
		"               ..               ",
		"               ..               ",
		"............   ..               ",
		"......................          ",
		"          ......................",
		"               ..   ............",
		"               ..               ",
		"               ..               ",
		"o             ...              o",
		"o             ...              o",
		"o             ..               o",
		"oo            ..              oo",
		"oo            ..              oo",
		"ooo           ..             ooo",
		"oooo          ..            oooo",
		"ooooo         ..           ooooo",
		"oooooo        ..          oooooo",
		"ooooooo       ..         ooooooo",
		"ooooooooo     ..       ooooooooo",
		"oooooooooooo  ..    oooooooooooo"
	}
};
