#include "powder.c"
#include "water.c"
#include "fire.c"
#include "seed.c"
#include "wood.c"
#include "gunpowder.c"
#include "fan.c"
#include "ice.c"
#include "snow.c"
#include "steam.c"
#include "superball.c"
#include "clone.c"
#include "fireworks.c"
#include "oil.c"
#include "c4.c"
#include "stone.c"
#include "magma.c"
#include "virus.c"
#include "nitro.c"

#include "thunder.c"
#include "metal.c"

#include "glass.c"
